### ISSUE TITLE
trouble compiling with 0.8.3

### ISSUE THREAD

**Issue by batchku** [astellato/ofxSyphon#16]
i'm trying to compile the basic example with 0.8.3 using the project generator

i'm copying the three source code files over to my new app folder:
main.cpp
ofApp.cpp
ofApp.h

i'm manually adding syphon.framework to "Link Binary with Libraries" as indicated in the previous issue posted to this board:

![image](https://cloud.githubusercontent.com/assets/518356/3562395/45135b5e-09ef-11e4-9b6d-379e4be8c551.png)

but i'm still getting compilations errors:

![image](https://cloud.githubusercontent.com/assets/518356/3562401/8ef00b3c-09ef-11e4-97a2-a0628fdf9bff.png)

**Comment by danrosero** [comment]
Anything new abut this? Im trying to get it working on 0.8.4.

**Comment by bangnoise** [comment]
This works in OF 0.9 and I will close this issue.

@danrosero and anyone using 0.8, read the README, carefully.

**Comment by danrosero** [comment]
@bangnoise Im getting " No member named 'glTypeInternal' in 'ofTextureData' " error.

**Comment by bangnoise** [comment]
READ THE READMEMEMEMEMEMEMEMEMEMEMEMEMEMEMEMEME

**Comment by bangnoise** [comment]
Particularly the second paragraph of the Installation section.

**Comment by bangnoise** [comment]
And once you've followed those instructions, read the README again, it will have changed.

**Comment by danrosero** [comment]
@bangnoise Thanks, all worked for me from 0.8 branch. Sorry lol.
